package com.adria.notification.models.enums.error;

import lombok.Getter;

/**
 * <p>Enumerator that covers detailed error codes and their default messages</p>
 * <p>These error codes used to provide an additional technical feedback</p>
 */
@Getter
public enum DetailedErrorCode {

    // Transactions related codes
    ERR_TR_0001("TRANSACTION_NOT_FOUND_ID"),
    ERR_TR_0002("TRANSACTION_NOT_FOUND_SIGNATURE_IMAGE"),
    ERR_TR_0003("TRANSACTION_NOT_FOUND_EVIDENCE_RECORD"),
    ERR_TR_0004("TRANSACTION_CREATION_VISIBLE_FAILED"),
    ERR_TR_0005("TRANSACTION_CREATION_INVISIBLE_FAILED"),
    ERR_TR_0006("TRANSACTION_APPROVAL_FAILED"),
    ERR_TR_0007("TRANSACTION_UNAUTHORIZED_APPROVAL_CANCEL"),
    ERR_TR_0008("TRANSACTION_UNAUTHORIZED_FINISH"),
    ERR_TR_0009("TRANSACTION_UNAUTHORIZED_KEYSTORE_OPERATION"),
    ERR_TR_0010("TRANSACTION_UNAUTHORIZED_PKCS11_OPERATION"),
    ERR_TR_0011("TRANSACTION_ORIGIN_MISS_MATCH"),
    ERR_TR_0012("TRANSACTION_NOT_FINISHED"),
    ERR_TR_0013("TRANSACTION_OTP_INCORRECT"),
    ERR_TR_0014("TRANSACTION_OTP_FAILED"),
    ERR_TR_0015("TRANSACTION_FAILED"),
    ERR_TR_0016("TRANSACTION_SIGNATURE_POSITION_OVERLAP_ERROR"),
    ERR_TR_0017("TRANSACTION_SIGNATURE_PARAMS_ERROR"),
    ERR_TR_0018("TRANSACTION_MAXIMUM_DOCUMENTS_ERROR"),
    ERR_TR_0019("TRANSACTION_OPTIMISTIC_LOCKING_FAILURE"),
    ERR_TR_0020("TRANSACTION_DOCUMENTS_SHOULD_VISUALIZE"),
    ERR_TR_0021("TRANSACTION_FILES_ERROR"),
    ERR_TR_0022("TRANSACTION_SIGNATURE_TSP_ERROR"),
    ERR_TR_0023("TRANSACTION_MAXIMUM_DOCUMENTS_ERROR"),
    ERR_TR_0024("TRANSACTION_KYC_SESSION_INVALID"),
    ERR_TR_0025("TRANSACTION_UNAUTHORIZED_RESET"),
    ERR_TR_0026("TRANSACTION_KYC_CONFIGURATION_MISSING_INFORMATION"),
    ERR_TR_0027("TRANSACTION_SIGNATURE_OPTIONS_MISSING"),
    ERR_TR_0028("TRANSACTION_UNAUTHORIZED_SEAL_OPERATION"),
    ERR_TR_0029("TRANSACTION_DOCUMENTS_NOT_COMPLETED"),
    ERR_TR_0030("TRANSACTION_FILES_INVALID"),
    ERR_TR_0031("TRANSACTION_FILES_TYPES_INVALID"),
    ERR_TR_0032("TRANSACTION_FILES_SIZE_INVALID"),
    ERR_TR_0033("TRANSACTION_FILES_MAX_NUMBER_ERROR"),
    ERR_TR_0034("UNAUTHORIZED_ADD_TRANSACTION"),
    ERR_TR_0035("ID_VERIFICATION_TRANSACTION_FILES_INVALID"),
    ERR_TR_0036("OCR_TRANSACTION_FILES_INVALID"),
    ERR_TR_0037("TRANSACTIONS_NUMBER_LIMIT_PER_DAY"),
    ERR_TR_0038("OCR_TRANSACTION_FILES_NOT_ACCEPTABLE"),

    // Application related codes
    ERR_APP_0001("CLIENT_APPLICATION_NOT_FOUND_ID"),
    ERR_APP_0002("CLIENT_APPLICATION_NOT_FOUND_CODE"),
    ERR_APP_0003("CLIENT_APPLICATION_INVALID"),
    ERR_APP_0004("CLIENT_APPLICATION_CREATION_FAILED"),
    ERR_APP_0005("CLIENT_APPLICATION_FAILED_AUTHENTICATION"),
    ERR_APP_0006("CLIENT_APPLICATION_LOCKED"),
    ERR_APP_0007("CLIENT_APPLICATION_SEAL_CONFIGURATION"),
    ERR_APP_0008("CLIENT_APPLICATION_UNAUTHORIZED"),
    ERR_APP_0009("CLIENT_APPLICATION_CODE_EXISTS"),
    ERR_APP_0010("CLIENT_APPLICATION_LABEL_EXISTS"),
    ERR_APP_0011("CLIENT_APPLICATION_BELONGS_TO_ANOTHER_CLIENT"),
    ERR_APP_0012("CLIENT_APPLICATION_FAILED_DELETE"),
    ERR_APP_0013("CLIENT_APPLICATION_NOT_ACTIVE"),
    ERR_APP_0014("APPLICATION_CLIENT_STATUS_DISABLED"),
    ERR_APP_0015("CLIENT_APPLICATION_CODE_NOT_VALID"),
    ERR_APP_0016("CLIENT_APPLICATION_SECRET_NOT_VALID"),

    // client related codes
    ERR_CL_0001("CLIENT_NOT_FOUND_ID"),
    ERR_CL_0002("CLIENT_COMPANY_NAME_EXISTS"),
    ERR_CL_0003("CLIENT_APPLICATION_BELONGS_TO_ANOTHER_ADMIN"),
    ERR_CL_0004("CLIENT_COULD_NOT_BE_DELETED"),

    // Account user related codes
    ERR_AU_0001("ACCOUNT_USER_NOT_FOUND_USER_NAME"),
    ERR_AU_0002("ACCOUNT_USER_NOT_FOUND_ID"),
    ERR_AU_0003("ACCOUNT_USER_FAILED_AUTHENTICATION"),
    ERR_AU_0004("ACCOUNT_USER_NAME_EXISTS"),
    ERR_AU_0005("ACCOUNT_USER_LOCKED"),
    ERR_AU_0006("ACCOUNT_USER_COULD_NOT_BE_DELETED"),
    ERR_AU_0007("FAILED_ACCESS_TOKEN"),
    ERR_AU_0008("ACCOUNT_USER_OLD_PASSWORD_INCORRECT"),
    ERR_AU_0009("ACCOUNT_USER_OLD_PASSWORD_MISSING"),
    ERR_AU_0010("ACCOUNT_USER_MISSING_INFORMATION"),
    ERR_AU_0011("ACCOUNT_USER_SUBSCRIPTION_EXPIRED"),
    ERR_AU_0012("ACCOUNT_USER_MAIL_NOT_VERIFIED"),
    ERR_AU_0013("ACCOUNT_USER_MAIL_ALREADY_VERIFIED"),
    ERR_AU_0014("ACCOUNT_USER_MAIL_VERIFICATION_RESEND_EXCEEDED"),
    ERR_AU_0015("ACCOUNT_USER_GOOGLE_RESPONSE_ERROR"),
    ERR_AU_0016("ACCOUNT_USER_CAPTCHA_MAXIMUM_ATTEMPTS"),
    ERR_AU_0017("ACCOUNT_USER_PASSWORD_RESET_RESEND_EXCEEDED"),
    ERR_AU_0018("ACCOUNT_USER_PASSWORD_RESET_TOKEN_INVALID"),
    ERR_AU_0019("ACCOUNT_USER_RESET_OLD_PASSWORD_MATCH"),
    ERR_AU_0020("FAILED_ACCOUNT_USER_EDIT"),
    ERR_AU_0021("ACCOUNT_USER_NEW_PASSWORD_MISSING"),
    ERR_AU_0022("USER_ACCOUNT_NOT_ACTIVE"),
    ERR_AU_0023("ACCOUNT_USER_NOT_ACCESSIBLE"),
    // Profile related codes
    ERR_PR_0001("PROFILE_NOT_FOUND_ID"),

    // Certification Authority related codes
    ERR_CA_0001("CERTIFICATION_AUTHORITY_NOT_FOUND_ID"),
    ERR_CA_0002("CERTIFICATION_AUTHORITY_NOT_FOUND_CODE"),
    ERR_CA_0003("CERTIFICATION_AUTHORITY_NOT_FOUND_ACTIVE"),

    // Endpoint related codes
    ERR_EP_0001("ENDPOINT_NOT_FOUND_ID"),
    ERR_EP_0002("ENDPOINT_NOT_FOUND_CODE"),
    ERR_EP_0003("ENDPOINT_DATA_INVALID"),

    // Document related codes
    ERR_DC_0001("DOCUMENT_NOT_FOUND_ID"),
    ERR_DC_0002("DOCUMENT_SIGNATURE_PAGE_ERROR"),
    ERR_DC_0003("PAGE_NUMBER_EXCEED_DOCUMENT"),
    ERR_DC_0004("DOCUMENT_SIGNATURE_ERROR"),
    ERR_DC_0005("DOCUMENT_MIMETYPE_ERROR"),

    // Evidence Record related codes
    ERR_ER_0001("EVIDENCE_RECORD_FAILED_DATA"),
    ERR_ER_0002("EVIDENCE_RECORD_FAILED_SEAL"),
    ERR_ER_0003("EVIDENCE_RECORD_FAILED_CONVERSION"),
    ERR_ER_0004("EVIDENCE_RECORD_NOT_GENERATED"),

    // Evidence File related codes
    ERR_EF_0001("EVIDENCE_FILE_NOT_FOUND"),
    ERR_EF_0002("EVIDENCE_FILE_DATA_MISMATCH"),
    ERR_EF_0003("EVIDENCE_FILE_DATA_MISMATCH"),

    // KeyStore related codes
    ERR_KS_0001("KEYSTORE_NOT_FOUND_ACTIVE_TRANSACTION"),
    ERR_KS_0002("KEYSTORE_NOT_FOUND_CERTIFICATE_TRANSACTION"),
    ERR_KS_0003("KEYSTORE_EXPIRED_CERTIFICATE"),

    // Directory related codes
    ERR_DR_0001("DIRECTORY_NOT_FOUND_CONTENT_TYPE"),
    ERR_DR_0002("DIRECTORY_NOT_FOUND_FULL_PATH"),
    // Screenshot related codes
    ERR_SS_0001("SCREENSHOT_NOT_FOUND_ID"),

    // StatusHistory related codes
    ERR_SH_0001("STATUS_HISTORY_NOT_FOUND_ID"),

    // ADTConst related codes
    ERR_AD_0001("ADT_CONST_NOT_FOUND_ID"),
    ERR_AD_0002("ADT_CONST_NOT_FOUND_CODE"),

    // Format related codes
    ERR_FM_0001("FORMAT_DIGEST_ALGORITHM_NOT_FOUND_CODE"),
    ERR_FM_0002("FORMAT_SIGNATURE_NOT_FOUND_CODE"),

    // Logging related codes
    ERR_LG_0001("LOGGING_FAILED"),
    ERR_LG_0002("LOGOUT_FAILED"),

    // Terms Of Use related codes
    ERR_TU_0001("TERMS_OF_USE_NOT_FOUND"),

    // TSP Authorities related codes
    ERR_TSP_0001("TSP_AUTHORITY_JKS_SECRET_MISSING"),
    ERR_TSP_0002("TSP_AUTHORITY_NOT_FOUND_ID"),
    ERR_TSP_0003("TSP_AUTHORITY_LABEL_EXISTS"),
    ERR_TSP_0004("TSP_AUTHORITY_JKS_FILE_MISSING"),
    ERR_TSP_0005("TSP_AUTHORITY_JKS_SECRET_INVALID"),

    // Generic File related codes
    ERR_FL_0001("FILE_NOT_FOUND"),
    ERR_FL_0002("FILE_FAILED_SAVE"),
    ERR_FL_0003("FILE_FAILED_DELETE"),
    ERR_FL_0004("FILE_FAILED_EXISTS"),
    ERR_FL_0005("FILE_FAILED_EMPTY"),
    ERR_FL_0006("FILE_FAILED_INVALID"),
    ERR_FL_0007("FILE_FAILED_SIZE"),
    ERR_FL_0008("FILE_FAILED_ENCRYPTED"),


    // Configuration related codes
    ERR_CF_0001("CONFIGURATION_FAILED_ESIGN_KEYSTORE"),
    ERR_CF_0002("CONFIGURATION_FAILED_ESIGN_SSL"),
    ERR_CF_0003("CONFIGURATION_FAILED_PDF_VALIDATOR"),

    // Keycloak error codes
    ERR_KY_0001("KEYCLOAK_NOT_FOUND_USER"),
    ERR_KY_0002("KEYCLOAK_EXPIRED_SUBSCRIPTION"),
    ERR_KY_0003("KEYCLOAK_FAILED_ACCESS_TOKEN"),
    ERR_KY_0004("KEYCLOAK_FAILED_CLIENT_CREATION"),
    ERR_KY_0005("KEYCLOAK_FAILED_CLIENT_UPDATE"),
    ERR_KY_0006("KEYCLOAK_FAILED_CLIENT_SECRET"),
    ERR_KY_0007("KEYCLOAK_FAILED_CLIENT_DELETE"),
    ERR_KY_0008("KEYCLOAK_FAILED_ACCOUNT_USER_CREATION"),
    ERR_KY_0009("KEYCLOAK_FAILED_ACCOUNT_USER_ROLE_ASSIGN"),
    ERR_KY_0010("KEYCLOAK_FAILED_ACCOUNT_USER_UPDATE"),
    ERR_KY_0011("KEYCLOAK_FAILED_ACCOUNT_USER_DELETE"),
    ERR_KY_0012("ACCESS_TOKEN_NOT_VALID"),
    ERR_KY_0013("TOKEN_CLIENT_ID_NOT_FOUND"),
    ERR_KY_0014("ACCESS_TOKEN_PARSE_FAILED"),
    ERR_KY_0015("CLIENT_ACCESS_TOKEN_NOT_VALID"),
    ERR_KY_0016("REFRESH_TOKEN_NOT_VALID"),
    // KYC error codes
    ERR_KYC_0001("KYC_FAILED_ACCESS_TOKEN"),
    ERR_KYC_0002("KYC_INVALID_PROVIDER"),
    ERR_KYC_0003("KYC_MISSING_PROVIDER_CONFIGURATIONS"),
    ERR_KYC_0004("KYC_SESSION_FAILED"),
    ERR_KYC_0005("KYC_SESSION_NOT_FOUND"),
    ERR_KYC_0006("KYC_SESSION_ALREADY_EXISTS"),
    ERR_KYC_0007("KYC_EXTERNAL_SERVICE_ERROR"),
    ERR_KYC_0008("KYC_SESSION_MATCHING_FAILED"),
    ERR_KYC_0009("KYC_SESSION_UNAUTHORIZED_PROVIDER"),
    ERR_KYC_0010("KYC_SESSION_EXPIRED"),
    ERR_KYC_0011("KYC_SESSION_INACCESSIBLE"),
    ERR_KYC_0012("KYC_SESSION_NON_RESETTABLE"),
    ERR_KYC_0013("KYC_CLIENT_TOKEN_PARSE_FAILED"),

    // KYC Configuration error
    ERR_KYCC_0001("SCOPE_CONFIGURATION_NOT_FOUND"),
    ERR_KYCC_0002("SCOPE_CONFIGURATION_DATA_INVALID"),
    ERR_KYCC_0003("KYC_CONFIGURATION_NOT_FOUND"),

    // Theme Configuration error
    ERR_THEME_0001("LINEAR_GRADIENT_STOP_NOT_FOUND"),
    ERR_THEME_0002("THEME_NOT_FOUND"),

    // System error codes
    ERR_SY_0001("SPRING_EXCEPTION"),
    ERR_SY_0002("PAYLOAD_TOO_LARGE"),
    ERR_SY_0003("SYSTEM_PARSE_ERROR"),
    ERR_SY_0004("SYSTEM_EXTERNAL_SERVICE_ERROR"),
    ERR_SY_0005("SYSTEM_GENERIC_SERVER_ERROR"),
    ERR_SY_0007("SYSTEM_ENCRYPTION_ERROR"),
    ERR_SY_0008("SYSTEM_DECRYPTION_ERROR"),

    ERR_GN_0000("GENERIC_ERROR");

    /**
     * <p>Error code description</p>
     */
    private final String description;

    DetailedErrorCode(String description) {
        this.description = description;
    }
}
